baseURL: 'https://blog.cmand.top'
languageCode: en-us
title: Vincent's Notes
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: GTM-KV7KW3LH

minify:
    disableXML: true
    minifyOutput: true

languages:
    en:
        title: Ming's Blog
        languageName: "English"
        weight: 1
        taxonomies:
          # category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Home
                  url: /
                  weight: 1
                - name: Archive
                  url: archives/
                  weight: 2
                - identifier: tags
                  name: Tags
                  url: tags/
                  weight: 3
                - identifier: search
                  name: Search
                  url: search/
                  weight: 4
                - name: About
                  url: about/
                  weight: 5
              
                

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    title: "Vincent's Notes"
    description: "Record, Share and Archive"
    keywords: [Blog, Technologic, Networking, Program, Travel, BGP]
    author: Vincent Young
    images: ["https://r2.qwq.mx/blog/20240331dCkqHY.jpg"]
    DateFormat: "Monday, January 2, 2006"
    defaultTheme: auto
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: false
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    TocOpen: true
    comments: true
    ShowAllPagesInArchive: true
    ShowFullTextinRSS: true

    mainSections:
        - posts

    profileMode:
        enabled: false

    homeInfoParams:
        Title: "Hi there 👋"
        Content: >
            I'm **Vincent Young**, operator of [AS206729](https://bgp.he.net/AS206729). I am a master student majoring in computer science at [University of Pittsburgh](https://www.pitt.edu). I am a **BGP** and **Linux** enthusiast, and an open source project contributor. You can get to know me on the [about](https://missuo.me/about) page.
    socialIcons:
        - name: github
          url: "https://github.com/chenming00"
        - name: twitter
          url: "https://twitter.com/Will_cm"
        - name: instagram
          url: "https://instagram.com/William_chenming"
        - name: discord
          url: "https://discordapp.com/users/mingisme2"
        - name: telegram
          url: "https://t.me/mingisme"
        - name: tiktok
          url: "https://www.tiktok.com/@mingchen895"
        - name: rss
          url: "https://missuo.me/index.xml"

    assets:
        disableHLJS: false
        favicon: "https://r2.qwq.mx/blog/20230104uZXT8s.ico"
        favicon16x16: "https://r2.qwq.mx/blog/20230104uZXT8s.ico"
        favicon32x32: "https://r2.qwq.mx/blog/20230104uZXT8s.ico"
        apple_touch_icon: "https://r2.qwq.mx/blog/20230104uZXT8s.ico"
        safari_pinned_tab: "https://r2.qwq.mx/blog/20230104uZXT8s.ico"

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: false
        style: darcula