baseURL: 'https://missuo.me'
languageCode: en-us
title: Vincent's Notes
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Home
                  url: /
                  weight: 1
                - name: Archive
                  url: archives/
                  weight: 2
                - identifier: tags
                  name: Tags
                  url: tags/
                  weight: 3
                - name: About
                  url: about/
                  weight: 4
                

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "Vincent's Notes"
    author: Vincent Young
    DateFormat: "January 2, 2006"
    defaultTheme: auto
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: false
    ShowRssButtonInSectionTermList: true
    ShowToc: false
    comments: true
    ShowAllPagesInArchive: true
    ShowFullTextinRSS: true
    images: ["papermod-cover.png"]

    mainSections:
        - posts

    profileMode:
        enabled: false

    homeInfoParams:
        Title: "Hi there 👋"
        Content: >
            I'm **Vincent Young**, operator of [AS206729](https://bgp.he.net/as206729). I am a computer science student and I am currently preparing my application for graduate school. I am a **BGP** and **Linux** enthusiast, and an open source project contributor. You can get to know me on the [about](https://missuo.me/about) page.
    socialIcons:
        - name: github
          url: "https://github.com/missuo"
        - name: twitter
          url: "https://twitter.com/m1ssuo"
        - name: instagram
          url: "https://instagram.com/m1ssuo"
        - name: discord
          url: "https://discordapp.com/users/missuo#7448"
        - name: telegram
          url: "https://t.me/missuo"
        - name: tiktok
          url: "https://www.tiktok.com/@m1ssuo"
        - name: youtube
          url: "https://youtube.com/@missuo"

    assets:
        disableHLJS: true
        favicon: "https://static.nisekoo.com/blog/20230104uZXT8s.ico"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: darcula
