name: Update US Visa Time Information

on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install httpx
          pip install pytz
      - name: Run Python
        run: |
          python scripts/update-visa.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: missuo
          commit_user_email: missuo@pm.me
          commit_message: Update US Visa Time